name: Build Package
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: Run inside Docker image
        run: |
          docker run ghcr.io/sebst/brewkit-test:latest --mount type=bind,source=$(pwd),target=/mnt /home/vscode/build.sh chezmoi.io 2.52.1
      - name: List files
        run: |
          ls -lah