name: Build Package
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: Run inside Docker image
        run: |
          docker run --rm \
          -e GITHUB_TOKEN=$GITHUB_TOKEN \
          -v $(pwd):/mnt \
          ghcr.io/sebst/brewkit-test:latest \
          /home/vscode/build.sh "chezmoi.io" "2.52.1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List files
        run: |
          ls -lah