name: Find Versions _optim_
on:
  workflow_dispatch:
  schedule: # Daily at 01:00 UTC
    - cron: '0 1 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt
      - name: Run tools/packageinfo_optim.py
        run: |
          cd tools
          rm -rf _optim_db.json
          rm -rf _optim_db-minified.json
          python packageinfo_optim.py
      - name: Commit changes
        run: |
          git config --global user.email "robot@bascodes.com"
          git config --global user.name "Robot"
          git add .
          git commit -m "Sync `pkgx.dev` pantry" || exit 0
          git push
