name: Sync `pkgx.dev` pantry
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Sync from `pkgx.dev`
        run: |
          rm -rf "${PANTRY_DIR_PKGX}"
          mkdir -p "${PANTRY_DIR_PKGX}"
          curl -sL "$PANTRY_TGZ_URL" | tar -xz -C "$PANTRY_DIR_PKGX" --strip-components=1 --wildcards '*/projects/*'
        env:
          PANTRY_TGZ_URL: "https://dist.pkgx.dev/pantry.tgz"
          PANTRY_DIR_PKGX: "./pantry/pkgx.dev"
      - name: List files
        run: |
          ls -lah pantry/pkgx.dev
      - name: Commit changes
        run: |
          git config --global user.email "robot@bascodes.com"
          git config --global user.name "Robot"
          git add pantry/pkgx.dev
          git commit -m "Sync `pkgx.dev` pantry"
          git push
