name: Sync `pkgx.dev` pantry
on:
  workflow_dispatch:
  schedule: # Daily at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt
      - name: Sync from `pkgx.dev`
        run: |
          rm -rf "${PANTRY_DIR_PKGX}"
          mkdir -p "${PANTRY_DIR_PKGX}"
          curl -sL "$PANTRY_TGZ_URL" | tar -xz -C "$PANTRY_DIR_PKGX" --strip-components=1 --wildcards '*/projects/*'
        env:
          PANTRY_TGZ_URL: "https://dist.pkgx.dev/pantry.tgz"
          PANTRY_DIR_PKGX: "./pantry/pkgx.dev"
      - name: Remoce Darwin Only Packages
        run: |
          python tools/remove_darwin_only.py
      - name: Commit changes
        run: |
          git config --global user.email "robot@bascodes.com"
          git config --global user.name "Robot"
          git add pantry/pkgx.dev
          git commit -m "Sync `pkgx.dev` pantry"
          git push
